### ISSUE TITLE
Shenfun cannot installed on Windows

### ISSUE THREAD

**Issue by sebglane** [conda-forge/shenfun-feedstock#19]
Issue: Shenfun cannot be installed using conda on Windows.

The following command doesn't work on my Windows machine:
```
$ conda install -c conda-forge shenfun
```
I think it is because there is simply no windows package available.

**Comment by mikaem** [comment]
Yes, there's no windows package available. This is because some required dependencies (like mpi4py) are not available on windows.

**Comment by sebglane** [comment]
Okay, thank you.
